name: Deploy to web
on:
  push:
    branches:
      - 'main'


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Set up Flutter.
      - name: Clone Flutter repository with master channel
        uses: subosito/flutter-action@48cafc24713cca54bbe03cdc3a423187d413aafa
        with:
          channel: master
      - run: flutter doctor -v

      # Checkout gallery code and get packages.
      - name: Checkout gallery code
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
      - run: flutter pub get

      # Build and deploy (by default, to staging).
      - run: flutter build -v web --release
      - run: ls

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: invectys
          password: 9dc98ef9-2eae-41fc-b11c-07b343cc4625

      - name: Build and push
        uses: docker/build-push-action@v2.10.0
        with:
          context: .
          push: true
          tags: invectys/tusa-control-panel-flutter:latest
  