name: Deploy to web
on:
  push:
    branches:
      - 'main'
//
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout gallery code
        uses: actions/checkout@v3
      - name: set up JDK 11
          uses: actions/setup-java@v2
          with:
            java-version: '11'
            distribution: 'adopt'
            cache: gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - run: ./gradlew assembleRelease
      - name: Save build
        uses: actions/upload-artifact@v2
        with:
          name: tusa-android
          path: app/build/outputs/apk/release/*.apk

  deploy:
    runs-on: regru-1
    needs: build
    steps:
      - name: Get artifcat
        uses: actions/download-artifact@v2
        with:
          name: tusa-android
      - run: mv *.apk /opt/tusa/nginx/files/android/